Adds in Data Validation Utility to rslabel package
PalouseRobosub/vision_dev pull request #19
Opened 2018-03-14 12:05 UTC by ryan-summers

The data validation utility was previously data_marker.py - However, now it has been added to the rslabel package flow. To validate annotations, run `rslabel mark [annotation_file]`. Help documents are displayed when the script begins.

2018-03-22 22:24 UTC, brennanpeter requested changes

2018-03-22 22:24 UTC, brennanpeter commented on rslabel_package/rslabel/marker.py
> +            continue
Delete continue

2018-03-22 22:24 UTC, brennanpeter commented on rslabel_package/rslabel/marker.py
> +        """ Initializes the image display.
If Scale could be adjutable that would be sweet. Right now it comes up on my screen a too small

2018-03-22 22:28 UTC, brennanpeter commented
Looks really good except for my 2 pet-peeves :+1: 
I'm not sure how many people we are going to have validating data, but it would be nice to have a system for less experienced validators to be able to say "I'm not sure for this picture, send it to daylan for validation" but that is really just a quality of life thing

2018-03-22 22:51 UTC, ryan-summers commented
Inexperienced validators with an image can just choose to skip it :)

2018-03-22 22:55 UTC, ryan-summers reviewed
Great points Peter, I'll update it when I wake up tomorrow :)

2018-03-23 17:24 UTC, brennanpeter approved these changes

2018-03-23 17:26 UTC, merged